column_width = 100
indent_type = "Tabs"
indent_width = 4
line_endings = "Unix"
quote_style = "AutoPreferDouble"
no_call_parentheses = false
no_semicolons = false
trailing_comma = "Always"
align_parameter = true
align_args = true
align_table_field = true
collapse_simple_statement = "Always"
